# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db6529da49ff5fe10607fc355bfed495f7a88047d0eb0a15a274d050565fdd9a34ed55ec02bb4c0fae00086c861b99094c53846d4cb2ee3db94449fb111b183e

test:
  secret_key_base: 56d293b278a0aa3b2ee8fc4ec67b4ad124b72debeac473e613a0db76078292ce1bfca10db1e8095832941d49395ec61545244c8333766cdd363c3f1d1241328d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
